=== NataliaBlancoAgudin/MotoGPDesktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" 
			elementFormDefault="qualified" 
			targetNamespace="http://www.uniovi.es" 
			xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horaSp" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="bibliografia" />
				<xs:element ref="galeria" />
				<xs:element ref="videos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacionMundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaSp" type="xs:time" />

	<xs:element name="numeroVueltas"> 
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />

	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="foto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="duracion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="duracion" type="xs:duration" />

	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="posicion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="posicion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="puntos" />
				<xs:element ref="pais" />
			</xs:sequence>
			<xs:attribute name="numero" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="puntos"> 
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== NataliaBlancoAgudin/MotoGPDesktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuitos xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <circuito>
        <nombre>Red Bull Ring - Spielberg</nombre>

        <longitudCircuito unidades="metros">4348</longitudCircuito>
        <anchura unidades="metros">12</anchura>

        <fecha>2025-08-17</fecha>
        <horaSp>14:00:00</horaSp>

        <numeroVueltas>28</numeroVueltas>

        <localidad>Spielberg</localidad>
        <pais>Austria</pais>

        <patrocinador>bwin</patrocinador>

        <bibliografia>
            <referencia descripcion="Calendario oficial de MotoGP">https://www.motogp.com/es/calendar/2025/event/austria/2691a49e-a593-4119-8fe4-826017d5f2dd?tab=overview</referencia>
            <referencia descripcion="Entradas para el circuito">https://tickets.motogp.com/es/21021-austria/</referencia>
            <referencia descripcion="Que saber antes de ir">https://www.tripadvisor.es/Attraction_Review-g2251638-d4584201-Reviews-Red_Bull_Ring-Spielberg_Styria.html</referencia>
        </bibliografia>

        <galeria>
            <foto descripcion="Foto Circuito">RedBullRing-Spielberg.jpg</foto>
            <foto descripcion="Dibujo circuito">RedBullRing-Spielberg-circuito.jpg</foto>
        </galeria>

        <videos>
            <video descripcion="Video explicativo">RedBullRing-Spilberg.mp4</video>
        </videos>

        <puntoOrigen>
            <longitud unidades="grados">14.76521632786185</longitud>
            <latitud unidades="grados">47.22002947008436</latitud>
            <altitud unidades="metros">678.1098045075122</altitud>
        </puntoOrigen>

        <tramos>
            <!-- c1-->
            <tramo>
                <distancia unidades="metros">160.77</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76521632786185</longitud>
                    <latitud unidades="grados">47.22002947008436</latitud>
                    <altitud unidades="metros">678.1098045075122</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c2-->
            <tramo>
                <distancia unidades="metros">151.66</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76317854426678</longitud>
                    <latitud unidades="grados">47.21963794124954</latitud>
                    <altitud unidades="metros">680.2439271580914</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c3-->
            <tramo>
                <distancia unidades="metros">22.14</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76126904972204</longitud>
                    <latitud unidades="grados">47.21927220598155</latitud>
                    <altitud unidades="metros">691.3542241462552</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c4-->
            <tramo>
                <distancia unidades="metros">18.66</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76098416568174</longitud>
                    <latitud unidades="grados">47.21923829960996</latitud>
                    <altitud unidades="metros">692.8233205380521</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c5-->
            <tramo>
                <distancia unidades="metros">94.76</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76082238843612</longitud>
                    <latitud unidades="grados">47.21936179589492</latitud>
                    <altitud unidades="metros">693.8723426206271</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c6-->
            <tramo>
                <distancia unidades="metros">173.32</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.76013527398485</longitud>
                    <latitud unidades="grados">47.22007660107175</latitud>
                    <altitud unidades="metros">696.9790523079205</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c7-->
            <tramo>
                <distancia unidades="metros">108.95</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75881257334475</longitud>
                    <latitud unidades="grados">47.22134863208055</latitud>
                    <altitud unidades="metros">697.5620318101106</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c8-->
            <tramo>
                <distancia unidades="metros">157.97</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75808989604139</longitud>
                    <latitud unidades="grados">47.22219535993467</latitud>
                    <altitud unidades="metros">699.0641732143366</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c9-->
            <tramo>
                <distancia unidades="metros">58.78</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75720736933028</longitud>
                    <latitud unidades="grados">47.2234803802053</latitud>
                    <altitud unidades="metros">701.2042212484656</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c10-->
            <tramo>
                <distancia unidades="metros">57.43</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75688507915911</longitud>
                    <latitud unidades="grados">47.22397075445713</latitud>
                    <altitud unidades="metros">704.0806787377568</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c11-->
            <tramo>
                <distancia unidades="metros">55.54</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75645996639228</longitud>
                    <latitud unidades="grados">47.22441332712304</latitud>
                    <altitud unidades="metros">708.9354614171937</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <!-- c12-->
            <tramo>
                <distancia unidades="metros">134.38</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75595276027208</longitud>
                    <latitud unidades="grados">47.22480408439441</latitud>
                    <altitud unidades="metros">713.7680827057038</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <!-- c13-->
            <tramo>
                <distancia unidades="metros">67.21</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75468845761633</longitud>
                    <latitud unidades="grados">47.22567445807532</latitud>
                    <altitud unidades="metros">731.5315228693939</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <!-- c14-->
            <tramo>
                <distancia unidades="metros">11.31</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75408105661262</longitud>
                    <latitud unidades="grados">47.2260910166864</latitud>
                    <altitud unidades="metros">741.1727672264944</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <!-- c15-->
            <tramo>
                <distancia unidades="metros">14.79</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75407356132155</longitud>
                    <latitud unidades="grados">47.22620050167087</latitud>
                    <altitud unidades="metros">743.3936486181128</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <!-- c16-->
            <tramo>
                <distancia unidades="metros">80.86</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75424783461644</longitud>
                    <latitud unidades="grados">47.226253837062</latitud>
                    <altitud unidades="metros">744.3758941073519</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="metros">54</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75530548156039</longitud>
                    <latitud unidades="grados">47.22634811821662</latitud>
                    <altitud unidades="metros">745.5745573622405</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="metros">86.64</distancia>
                <coordenadas>
                    <longitud unidades="grados">14.75601536223006</longitud>
                    <latitud unidades="grados">47.22645158467185</latitud>
                    <altitud unidades="metros">743.7022446470598</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="metros">159.25</distancia>
                <coordenadas>
